# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20170108_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(max_length=300)),
                ('delete_date', models.DateField(default=datetime.datetime(2017, 2, 17, 5, 7, 55, 834233))),
            ],
        ),
    ]
