# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_authorizationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationtoken',
            name='name',
            field=models.CharField(default='New Token', max_length=200),
        ),
        migrations.AlterField(
            model_name='authorizationtoken',
            name='delete_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 17, 5, 9, 17, 41879)),
        ),
    ]
